spring:
  application:
    name: atcrowdfunding-project
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.132.7:3306/atcrowdfunding?serverTimezone=UTC

  redis:
    host: 192.168.132.7


eureka:
  client:
    register-with-eureka: true #注册到注册中心中
    fetch-registry: true #从注册中心中获取数据
    service-url:
      defaultZone: http://localhost:8761/eureka #注册中心的地址
  instance:
    prefer-ip-address: true #使用ip注册进去

server:
  port: 8000